spring:
  datasource:
    url: jdbc:postgresql://database:5432/cda
    password: cda
    username: cda
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect