version: "3.7"

services:
  database:
    container_name: cda-postgres
    restart: always
    hostname: database
    image: "postgres:12.15-alpine"
    expose:
      - "5432"
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_DB=cda
      - POSTGRES_USER=cda
      - POSTGRES_PASSWORD=cda
    volumes:
      - cda_pgsql_data:/var/lib/postgresql/data
    networks:
      - cda-app
    privileged: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW

  backend:
    image: "cda-backend"
    build:
      dockerfile: docker/Dockerfile
      context: ../
    depends_on:
      - database
    container_name: cda-backend
    restart: always
    environment:
      - TZ=Europe/Warsaw
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - cda-app
    privileged: false
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - NET_RAW

networks:
  cda-app:

volumes:
  cda_pgsql_data:
